import StoreProvider from "@/app/hooks/StoreProvider";
import { IUser } from "@/app/types/user.types";
import CookieSetter from "@/components/CookieSetter";
import ConditionalNavbar from "@/components/Navbar/ConditionalNavbar";
import NotificationProvider from "@/Context/NotificationContext";
import { UserDataProvider } from "@/Context/UserDataContext";
import { DEFAULT_API_URL } from "@/lib/config";
import NextAuthSessionProvider from "@/provider/NextAuthSessionProvider";
import ReactQueryProvider from "@/provider/ReactQueryProvider";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { cookies } from "next/headers";
import { ReactNode } from "react";
import "./globals.css";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  let user = null;

  try {
    const cookieStore = await cookies();
    const access_token = cookieStore.get("access_token")?.value;

    if (access_token) {
      const res = await fetch(`${DEFAULT_API_URL}/api/user`, {
        method: "GET",
        headers: {
          "Content-Type": "application/json",
          Cookie: `access_token=${access_token}`,
        },
        credentials: "include",
      });
      if (res.ok) {
        const response = await res.json() as IUser;
        user = response?.data || null;

      } else {
        console.error("Failed to fetch user:", res.status, res.statusText);
      }
    }
  } catch (error) {
    console.error("Failed to fetch user in layout:", error);
  }

  return (
    <html lang="en" className={`${roboto.className}`}>
      <body className={`antialiased`}>
        <NextAuthSessionProvider>
          <StoreProvider>
            <ReactQueryProvider>
              <UserDataProvider initialUser={user}>
                <NotificationProvider>
                  <CookieSetter userId={user?.id || null} />
                  <ConditionalNavbar />
                  {children}
                </NotificationProvider>
              </UserDataProvider>
            </ReactQueryProvider>
          </StoreProvider>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
